### ISSUE TITLE
Use commit merge in merge_into.sh instead of squash and merge 

### ISSUE THREAD

**Issue by Yogesh-K-Tern** [akshayrao14/git-practices#3]
doing squash and merge is always creating new commit with new hash which make developers resolve conflict everytime they merge thier code in any branch, by doing it with commit and merge dev always have to resolve conflict only once after they can just merge and can be Happy!

How I Do..... steps
- checkout from _feature branch_ to _env branch (dev, demo ,...)_ 
- take a pull 
- run command git merge _feature branch_
- finally _git push_
- checkout to _feature branch_

**Comment by akshayrao14** [comment]
accepted

**Comment by akshayrao14** [comment]
Handled in #9
